# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb7e894d94bdbfd08c2ef4cf8d43d968c7d1bdcb9b7a23e18410715b7a045f56926daa9771f44e6139c07d12e360a9fdebdcff07f651271dff48e8f9f1fe47fd

test:
  secret_key_base: 66daa63a8ba4501221b55f62f504d77576c08d6a6a73f15853d87975cf2d43ad613d881d980f08f2eeb52fef713fea369a575843ec1e7bdae3fa521a13d6e95e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
